spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cnkart
    username: root
    password: 12345

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update

server:
  port: 7070